---
- name: Install mpd
  block:
    - name: Install mpd packages
      become: true
      apt:
        name: "{{ mpd_packages }}"
        state: present
        update_cache: true

    - name: Create mpd folders
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - ~/.config
        - ~/.config/ncmpcpp
        - ~/.local
        - ~/.local/bin
        - ~/.mpd
        - ~/.mpd/playlists
        - ~/Music

    - name: Configure mpd
      template:
        src: .mpdconf.j2
        dest: ~/.mpdconf
        mode: 0644

    - name: Disable system-wide mpd
      become: true
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - mpd.service
        - mpd.socket

    - name: Configure ncmpcpp
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      loop:
        - {src: .config/ncmpcpp/config.j2, dest: ~/.config/ncmpcpp/config, mode: '0644'}
        - {src: .local/bin/songinfo.j2, dest: ~/.local/bin/songinfo, mode: '0755'}
  when:
    - install_mpd
  tags:
    - music
    - mpd

- name: Install Spotify
  block:
    - name: Get Spotify repository key
      become: true
      get_url:
        url: https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg
        dest: /etc/apt/keyrings/spotify.asc
        mode: '0644'
      register: spotify_key

    - name: Unpack GPG file from ASCII key
      become: true
      shell: gpg -o /etc/apt/keyrings/spotify.gpg --dearmor /etc/apt/keyrings/spotify.asc
      when:
        - spotify_key.changed

    - name: Add Spotify repository
      become: true
      apt_repository:
        filename: spotify
        repo: "deb [signed-by=/etc/apt/keyrings/spotify.gpg]
          http://repository.spotify.com stable non-free"

    - name: Install Spotify
      become: true
      apt:
        name: spotify-client
        state: present
        update_cache: true

    - name: Create Spotify desktop file
      become: true
      template:
        src: usr/share/applications/spotify.desktop.j2
        dest: /usr/share/applications/spotify.desktop
        mode: '0644'
  when:
    - install_spotify
  tags:
    - music
    - spotify
