---
- name: Install awscli
  block:
    - name: Get awscli archive
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip

    - name: Unzip archive
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: true

    - name: Install awscli
      become: true
      command: /tmp/aws/install -i /usr/local/aws-cli -b /usr/local/bin
  when:
    - install_devops_tools
  tags:
    - awscli
