---
window_managers_install_awesomewm: false
window_managers_install_i3: false
window_managers_install_qtile: false

window_managers_awesomewm_widget_url: "https://github.com/streetturtle/awesome-wm-widgets.git"
window_managers_awesomewm_widget_version: "28da705c60c01235899309d5cd6c2e7e727db498"
window_managers_awesomewm_arc_icon_url: "https://github.com/horst3180/arc-icon-theme"
window_managers_awesomewm_arc_icon_version: "20161122"

window_managers_qtile_version: "v0.36.0"

window_managers_wallpapers_repo_url: "git@github.com:djeeks1/wallpapers.git"
window_managers_wallpapers_repo_version: "v0.0.1"

window_managers_awesomewm_packages:
  - awesome
  - awesome-extra
  - compton
  - i3lock
  - light
  - nitrogen
  - xss-lock

window_managers_i3_packages:
  - compton
  - i3
  - i3lock
  - nitrogen
  - xss-lock
  - imagemagick

window_managers_qtile_packages:
  - compton
  - i3lock
  - libiw-dev
  - libpangocairo-1.0-0
  - libxkbcommon-dev
  - nitrogen
  - python3-cairocffi
  - python3-pip
  - python3-venv
  - python3-xcffib
  - xinit
  - xserver-xorg
  - xss-lock
  - imagemagick
