---
- name: Remove Firefox ESR
  become: true
  apt:
    name: firefox-esr
    state: absent
  tags:
    - firefox
    - web-browsers

- name: Install Firefox from unstable repo
  become: true
  apt:
    name: firefox
    state: present
    update_cache: true
  tags:
    - firefox
    - web-browsers

- name: Add Google repository's key
  become: true
  get_url:
    url: https://dl.google.com/linux/linux_signing_key.pub
    dest: /etc/apt/keyrings/dl.google.com.pub
    mode: 0644
    force: yes
  tags:
    - google-chrome
    - web-browsers

- name: Add Google repository
  become: true
  apt_repository:
    filename: google-chrome
    repo: 'deb [signed-by=/etc/apt/keyrings/dl.google.com.pub] http://dl.google.com/linux/chrome/deb/ stable main'
  tags:
    - google-chrome
    - web-browsers

- name: Install Google Chrome
  become: true
  apt:
    name: google-chrome-stable
    state: present
    update_cache: true
  tags:
    - google-chrome
    - web-browsers
