---
- name: Install kitty
  become: true
  apt:
    name: kitty
    state: present
    update_cache: true
  tags:
    - kitty

- name: Create kitty folders
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  loop:
    - ~/.config
    - ~/.config/kitty
  tags:
    - kitty

- name: Deploy kitty config file
  template:
    src: .config/kitty/kitty.conf.j2
    dest: ~/.config/kitty/kitty.conf
    mode: 0640
  tags:
    - kitty
