---
tools_install_optional: false

tools_default_packages:
  - alsa-utils
  - apt-transport-https
  - bash-completion
  - build-essential
  - bind9-dnsutils
  - ca-certificates
  - ccze
  - cups
  - curl
  - direnv
  - evince
  - filezilla
  - fonts-font-awesome
  - gcal
  - htop
  - hyphen-fr
  - ipcalc
  - jq
  - keepassxc
  - libreoffice-calc
  - libreoffice-writer
  - locate
  - lsb-release
  - mtr
  - ncdu
  - network-manager
  - nmap
  - psmisc
  - pwgen
  - python3-packaging
  - python3-pip
  - python3-venv
  - screen
  - sslscan
  - strace
  - sysstat
  - tcpdump
  - telnet
  - traceroute
  - tig
  - tree
  - unzip
  - vlc
  - wget
  - whois

tools_additional_packages:
  - autorandr
  - bluez-firmware
  - firmware-linux
  - firmware-linux-free
  - firmware-linux-nonfree
  - flameshot
  - pavucontrol
  - pulseaudio
  - pulseaudio-module-bluetooth
  - ristretto
  - thunar
  - xorg

tools_optional_packages:
  - nextcloud-desktop
