---
- name: Install kubernetes tools
  become: true
  when:
    - install_devops_tools
  tags:
    - k8s_tools
  block:
    - name: Get kubernetes repo key
      ansible.builtin.get_url:
        url: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_tools_k8s_version }}/deb/Release.key"
        dest: /etc/apt/keyrings/kubernetes-apt-keyring
        mode: '0644'
        force: true
      notify: Pack k8s GPG file from ASCII key

    - name: Pack GPG file right now
      ansible.builtin.meta: flush_handlers

    - name: Add kubernetes repo
      ansible.builtin.apt_repository:
        filename: kubernetes
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg]
          https://pkgs.k8s.io/core:/stable:/v{{ k8s_tools_k8s_version }}/deb/ /"

    - name: Install kubectl
      ansible.builtin.apt:
        name: kubectl
        state: present
        update_cache: true

    - name: Get Helm repo key
      ansible.builtin.get_url:
        url: https://packages.buildkite.com/helm-linux/helm-debian/gpgkey
        dest: /etc/apt/keyrings/helm
        mode: '0644'
        force: true
      notify: Pack Helm GPG file from ASCII key

    - name: Pack GPG file right now
      ansible.builtin.meta: flush_handlers

    - name: Add Helm repository
      ansible.builtin.apt_repository:
        filename: helm
        repo: 'deb [signed-by=/etc/apt/keyrings/helm.gpg]
          https://packages.buildkite.com/helm-linux/helm-debian/any/ any main'

    - name: Install Helm
      ansible.builtin.apt:
        name: helm
        state: present
        update_cache: true

    - name: Get k9s archive
      ansible.builtin.unarchive:
        src: "{{ k8s_tools_k9s.url }}"
        dest: /tmp/
        remote_src: true
        owner: root

    - name: Move k9s to PATH
      ansible.builtin.copy:
        src: /tmp/k9s
        dest: /usr/local/bin/k9s
        owner: root
        group: root
        mode: '0755'

    - name: Ensure k9s confdir exists
      become: false
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - ~/.config/k9s
        - ~/.config/k9s/skins

    - name: Get k9s theme
      become: false
      ansible.builtin.get_url:
        url: "{{ k8s_tools_k9s.theme_url }}"
        dest: "~/.config/k9s/skins/{{ k8s_tools_k9s.theme_name }}.yaml"
        mode: '0644'

    - name: Configure k9s
      become: false
      ansible.builtin.template:
        src: .config/k9s/config.yaml.j2
        dest: ~/.config/k9s/config.yaml
        mode: '0644'
