---
- name: Install dunst
  become: true
  apt:
    name: dunst
    state: present
    update_cache: true
  tags:
    - awesomewm
    - i3
    - qtile
    - dunst

- name: Create dunst folders
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - ~/.config
    - ~/.config/dunst
  tags:
    - awesomewm
    - i3
    - qtile
    - dunst

- name: Deploy dunst configuration file
  template:
    src: .config/dunst/dunstrc.j2
    dest: ~/.config/dunst/dunstrc
    mode: 0644
  tags:
    - awesomewm
    - i3
    - qtile
    - dunst
