---
- name: Install mpd
  import_tasks: mpd.yml
  tags:
    - mpd

- name: Install Display Manager
  import_tasks: display_manager.yml
  tags:
    - awesomewm
    - i3
    - qtile
    - display_manager

- name: Install and configure AwesomeWM
  import_tasks: awesomewm.yml
  when:
    - install_awesomewm
  tags:
    - awesomewm

- name: Install and configure i3
  import_tasks: i3.yml
  when:
    - install_i3 
  tags:
    - i3

- name: Install and configure qtile
  import_tasks: qtile.yml
  when:
    - install_qtile
  tags:
    - qtile

- name: Install and configure dunst
  import_tasks: dunst.yml
  tags:
    - awesomewm
    - i3
    - qtile
    - dunst

- name: Deploy Wallpapers
  import_tasks: wallpapers.yml
  tags:
    - awesomewm
    - i3
    - qtile

- name: Install Rofi
  import_tasks: rofi.yml
  when:
    - install_i3 or install_awesomewm or install_qtile
  tags:
    - awesomewm
    - i3
    - qtile
    - rofi

- name: Install Polybar
  import_tasks: polybar.yml
  when:
    - install_i3
  tags:
    - i3
    - polybar
