---
- name: Install Display Manager
  ansible.builtin.import_tasks: display_manager.yml
  when:
    - window_managers_install_i3 or window_managers_install_awesomewm or window_managers_install_qtile
  tags:
    - awesomewm
    - i3
    - qtile
    - display_manager

- name: Install and configure AwesomeWM
  ansible.builtin.import_tasks: awesomewm.yml
  when:
    - window_managers_install_awesomewm
  tags:
    - awesomewm

- name: Install and configure i3
  ansible.builtin.import_tasks: i3.yml
  when:
    - window_managers_install_i3
  tags:
    - i3

- name: Install and configure qtile
  ansible.builtin.import_tasks: qtile.yml
  when:
    - window_managers_install_qtile
  tags:
    - qtile

- name: Install and configure dunst
  ansible.builtin.import_tasks: dunst.yml
  when:
    - window_managers_install_i3 or window_managers_install_awesomewm or window_managers_install_qtile
  tags:
    - awesomewm
    - i3
    - qtile
    - dunst

- name: Deploy Wallpapers
  ansible.builtin.import_tasks: wallpapers.yml
  tags:
    - awesomewm
    - i3
    - qtile

- name: Install Rofi
  ansible.builtin.import_tasks: rofi.yml
  when:
    - window_managers_install_i3 or window_managers_install_awesomewm or window_managers_install_qtile
  tags:
    - awesomewm
    - i3
    - qtile
    - rofi

- name: Install Polybar
  ansible.builtin.import_tasks: polybar.yml
  when:
    - window_managers_install_i3
  tags:
    - i3
    - polybar
