---
- name: Install mpd
  import_tasks: mpd.yml
  tags:
    - mpd

- name: Install Display Manager
  import_tasks: display_manager.yml
  tags:
    - awesomewm
    - i3
    - display_manager

- name: Install and configure AwesomeWM
  import_tasks: awesomewm.yml
  when:
    - install_awesomewm
  tags:
    - awesomewm

- name: Install and configure i3
  import_tasks: i3.yml
  when:
    - install_i3 
  tags:
    - i3

- name: Deploy Wallpaper
  import_tasks: wallpaper.yml
  tags:
    - awesomewm
    - i3

- name: Install Rofi
  import_tasks: rofi.yml
  when:
    - install_i3 or install_awesomewm
  tags:
    - awesomewm
    - i3
    - rofi

- name: Install Polybar
  import_tasks: polybar.yml
  when:
    - install_i3
  tags:
    - i3
    - polybar
