---
- name: Install mpd
  become: true
  apt:
    name: "{{ mpd_packages }}"
    state: present
    update_cache: true
  tags:
    - mpd

- name: Create mpd folders
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  loop:
    - ~/.config
    - ~/.config/ncmpcpp
    - ~/.mpd
    - ~/.mpd/playlists
    - ~/Music
  tags:
    - mpd

- name: Configure mpd
  template:
    src: .mpdconf.j2
    dest: ~/.mpdconf
    mode: 0640
  tags:
    - mpd

- name: Disable system-wide mpd
  become: true
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
    - mpd.service
    - mpd.socket
  tags:
    - mpd

- name: Configure ncmpcpp
  template:
    src: .config/ncmpcpp/config.j2
    dest: ~/.config/ncmpcpp/config
    mode: 0640
  tags:
    - mpd
