---
- name: Clone wallpapers repository
  ansible.builtin.git:
    repo: "{{ window_managers_wallpapers_repo_url }}"
    dest: ~/Pictures/wallpapers
    version: "{{ window_managers_wallpapers_repo_version }}"
  tags:
    - awesomewm
    - i3
    - qtile
    - wallpapers
