---
- name: Install Hashicorp tools
  become: true
  when:
    - install_devops_tools
  tags:
    - hashicorp-tools
  block:
    - name: Get Hashicorp repository key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /etc/apt/keyrings/apt.releases.hashicorp.com
        mode: '0644'
        force: true
      notify: Pack Hashicorp GPG file from ASCII key

    - name: Pack GPG file right now
      ansible.builtin.meta: flush_handlers

    - name: Add Hashicorp repository
      ansible.builtin.apt_repository:
        filename: hashicorp
        repo: 'deb [signed-by=/etc/apt/keyrings/apt.releases.hashicorp.com.gpg]
          https://apt.releases.hashicorp.com bullseye main'

    - name: Install Hashicorp tools
      ansible.builtin.apt:
        name: "{{ hashicorp_tools_packages }}"
        state: present
        update_cache: true
