---
- name: Setting /etc/apt/preferences
  become: true
  template:
    src: etc/apt/preferences.j2
    dest: /etc/apt/preferences
    mode: 0644

- name: Setting sources.list
  become: true
  template:
    src: etc/apt/sources.list.j2
    dest: /etc/apt/sources.list
    mode: 0644

- name: Install packages
  become: true
  apt:
    name: "{{ default_packages }}"
    state: present
    update_cache: true

- name: Remove Firefox ESR
  become: true
  apt:
    name: firefox-esr
    state: absent

- name: Install Firefox from unstable repo
  become: true
  apt:
    name: firefox
    state: present
    update_cache: true
    default_release: unstable

- name: Add Google repository
  become: true
  template:
    src: etc/apt/sources.list.d/google.list.j2
    dest: /etc/apt/sources.list.d/google.list
    mode: 0644

- name: Add Google repository's key
  become: true
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    id: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991
    state: present

- name: Install Google Chrome
  become: true
  apt:
    name: google-chrome-stable
    state: present
    update_cache: true

- name: Ensure .ssh directory exists
  file:
    path: ~/.ssh
    state: directory
    mode: 0700

- name: Setting SSH options
  template:
    src: .ssh/config.j2
    dest: ~/.ssh/config
    mode: 0600

- name: Configure Git globally
  template:
    src: .gitconfig.j2
    dest: ~/.gitconfig
    mode: 0640
