---
- name: Setting sources.list
  become: true
  ansible.builtin.template:
    src: etc/apt/sources.list.j2
    dest: /etc/apt/sources.list
    mode: '0644'
  when: ansible_facts[distribution] == 'Debian'
  tags:
    - apt
    - tools

- name: Set tools_full_packages
  ansible.builtin.set_fact:
    tools_full_packages: "{{ tools_default_packages }}"
  when: ansible_facts[distribution] == 'Ubuntu'
  tags:
    - apt
    - tools

- name: Set tools_full_packages
  ansible.builtin.set_fact:
    tools_full_packages: "{{ tools_default_packages + tools_additional_packages }}"
  when: ansible_facts[distribution] == 'Debian'
  tags:
    - apt
    - tools

- name: Install packages
  become: true
  ansible.builtin.apt:
    name: "{{ tools_full_packages }}"
    state: present
    update_cache: true
  tags:
    - apt
    - tools

- name: Install optional packages
  become: true
  ansible.builtin.apt:
    name: "{{ tools_optional_packages }}"
    state: present
    update_cache: true
  when:
    - tools_install_optional
  tags:
    - apt
    - tools

- name: Create virtualenvs directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - ~/virtualenvs
    - ~/virtualenvs/default
  tags:
    - bashrc
    - tools

- name: Create default virtualenv
  ansible.builtin.command:
    cmd: "python3 -m venv ~/virtualenvs/default"
  changed_when: false
  tags:
    - bashrc
    - tools

- name: Update .bashrc file
  ansible.builtin.template:
    src: .bashrc.j2
    dest: ~/.bashrc
    mode: '0640'
  tags:
    - bashrc
    - tools

- name: Update PATH with user bin
  ansible.builtin.template:
    src: .xsessionrc.j2
    dest: ~/.xsessionrc
    mode: '0640'
  tags:
    - xsessionrc
    - tools

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    mode: '0700'
  tags:
    - ssh
    - tools

- name: Set SSH options
  ansible.builtin.template:
    src: .ssh/config.j2
    dest: ~/.ssh/config
    mode: '0600'
  tags:
    - ssh
    - tools

- name: Configure Git globally
  ansible.builtin.template:
    src: .gitconfig.j2
    dest: ~/.gitconfig
    mode: '0640'
  tags:
    - git
    - tools

- name: Create config dir
  ansible.builtin.file:
    path: ~/.config/direnv
    state: directory
    mode: '0700'
  tags:
    - direnv
    - tools

- name: Configure direnv
  ansible.builtin.template:
    src: .config/direnv/direnv.toml.j2
    dest: ~/.config/direnv/direnv.toml
    mode: '0640'
  tags:
    - direnv
    - tools
