---
- name: Setting sources.list
  become: true
  template:
    src: etc/apt/sources.list.j2
    dest: /etc/apt/sources.list
    mode: 0644

- name: Install packages
  become: true
  apt:
    name: "{{ default_packages }}"
    state: present
    update_cache: true
