---
- name: Setting /etc/apt/preferences
  become: true
  template:
    src: etc/apt/preferences.j2
    dest: /etc/apt/preferences
    mode: 0644
  tags:
    - apt
    - tools

- name: Setting sources.list
  become: true
  template:
    src: etc/apt/sources.list.j2
    dest: /etc/apt/sources.list
    mode: 0644
  tags:
    - apt
    - tools

- name: Install packages
  become: true
  apt:
    name: "{{ default_packages }}"
    state: present
    update_cache: true
  tags:
    - apt
    - tools

- name: Update .bashrc file
  template:
    src: .bashrc.j2
    dest: ~/.bashrc
    mode: 0640
  tags:
    - bashrc
    - tools

- name: Update PATH with user bin
  template:
    src: .xsessionrc.j2
    dest: ~/.xsessionrc
    mode: 0640
  tags:
    - xsessionrc
    - tools

- name: Ensure .ssh directory exists
  file:
    path: ~/.ssh
    state: directory
    mode: 0700
  tags:
    - ssh
    - tools

- name: Set SSH options
  template:
    src: .ssh/config.j2
    dest: ~/.ssh/config
    mode: 0600
  tags:
    - ssh
    - tools

- name: Configure Git globally
  template:
    src: .gitconfig.j2
    dest: ~/.gitconfig
    mode: 0640
  tags:
    - git
    - tools
