---
- name: Install Docker
  become: true
  when:
    - install_devops_tools
  tags:
    - docker
  block:
    - name: Get Docker repository key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/download.docker.com
        mode: '0644'
        force: true
      notify: Pack Docker GPG file from ASCII key

    - name: Pack GPG file right now
      ansible.builtin.meta: flush_handlers

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        filename: docker
        repo: 'deb [signed-by=/etc/apt/keyrings/download.docker.com.gpg]
          https://download.docker.com/linux/debian bookworm stable'

    - name: Install Docker
      ansible.builtin.apt:
        name: "{{ docker_packages }}"
        state: present
        update_cache: true
