---
- name: Install Starship Prompt
  become: true
  unarchive:
    src: "{{ starship.url }}"
    dest: /usr/local/bin
    remote_src: yes
    owner: root
    group: staff
    mode: 0755
  tags:
    - starship

- name: Install glyph rendering fonts
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - fonts-powerline
    - fonts-noto-color-emoji
  tags:
    - starship

- name: Ensure .config directory exists
  file:
    path: ~/.config
    state: directory
    mode: 0750
  tags:
    - starship

- name: Set Starship configuration
  template:
    src: .config/starship.toml.j2
    dest: ~/.config/starship.toml
    mode: 0640
  tags:
    - starship
