---
- name: Install Starship Prompt
  block:
    - name: Install Starship Prompt
      become: true
      unarchive:
        src: "{{ starship.url }}"
        dest: /usr/local/bin
        remote_src: true
        owner: root
        group: staff
        mode: 0755

    - name: Install glyph rendering fonts
      become: true
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - fonts-powerline
        - fonts-noto-color-emoji

    - name: Ensure .config directory exists
      file:
        path: ~/.config
        state: directory
        mode: 0750

    - name: Set Starship configuration
      template:
        src: .config/starship.toml.j2
        dest: ~/.config/starship.toml
        mode: 0640
  when:
    - install_starship
  tags:
    - starship
