---
- name: Install Vim
  become: true
  apt:
    name: vim
    state: present
    update_cache: true
  tags:
    - vim

- name: Update editor alternative
  become: true
  alternatives:
    name: editor
    path: /usr/bin/vim
  tags:
    - vim

- name: Install linter
  become: true
  apt:
    name: "{{ linter_packages }}"
    state: present
    update_cache: true
  tags:
    - vim

- name: Install linter (via pip)
  pip:
    name: "{{ linter_pip_packages }}"
    state: present
    extra_args: --user
  tags:
    - vim

- name: Configure Vim
  template:
    src: .vimrc.j2
    dest: ~/.vimrc
    mode: 0640
  tags:
    - vim

- name: Create plugins folder
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.vim
    - ~/.vim/pack
    - ~/.vim/pack/plugins
    - ~/.vim/pack/plugins/start
  tags:
    - vim

- name: Install plugins
  git:
    repo: "{{ item.value.url }}"
    dest: "~/.vim/pack/plugins/start/{{ item.key }}"
    depth: 1
  with_dict:
    - "{{ vim_plugins }}"
  tags:
    - vim
