---
- name: Install Vim
  become: true
  apt:
    name: vim
    state: present
    update_cache: true

- name: Configure Vim
  template:
    src: .vimrc.j2
    dest: ~/.vimrc
    mode: 0640

- name: Install linter
  become: true
  apt:
    name: "{{ linter_packages }}"
    state: present
    update_cache: true
