---
- name: Install rofi
  become: true
  apt:
    name: rofi
    state: present
    update_cache: true
  tags:
    - awesomewm
    - i3
    - rofi

- name: Create rofi config folder
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  loop:
    - ~/.config/rofi
  tags:
    - awesomewm
    - i3
    - rofi

- name: Deploy rofi config file
  template:
    src: .config/rofi/config.rasi.j2
    dest: ~/.config/rofi/config.rasi
    mode: 0640
  tags:
    - awesomewm
    - i3
    - rofi
